Fingeso/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
import settings

admin.autodiscover()



urlpatterns = [
        url(r'^admin/', include(admin.site.urls)),
        url(r'^$', 'Fingeso.views.home', name='home'),
        url(r'^rajim/', include('rajim.urls')),
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]

rajim/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rajim import views

urlpatterns = [
    url(r'^Disco/(?P<id_disco>.*)/$', views.Album),
    url(r'^BusquedaDisco.html$', views.BusquedaAlbum),
    url(r'^Contacto.html$', views.Contacto),
    url(r'^Registrar.html$', views.Registrar),
    url(r'^Ingresar.html$', views.Ingresar),
    url(r'^Ranking.html$', views.Ranking),
    url(r'^Registrar2.html$', views.Registrar2),
    url(r'^CerrarSesion.html$', views.CerrarSesion),
    url(r'^Perfil.html$', views.Perfil),
    url(r'^EditarPerfil.html$', views.EditarPerfil),
    url(r'^Artista/(?P<id_artista>.*)/$', views.Artistas),
    url(r'^BusquedaArtista.html$', views.BusquedaArtista),




]

rajim/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

def url3(self, filename):
        ruta = "Artistas/%s/%s" % (self.nombre_artista, str(filename))
        return ruta

class Artista(models.Model):
    
    id_artista = models.AutoField(db_column='ID_ARTISTA', primary_key=True)  # Field name made lowercase.
    nombre_artista = models.CharField(db_column='NOMBRE_ARTISTA', max_length=60, blank=True, null=True)  # Field name made lowercase.
    resena = models.TextField(db_column='RESENA', max_length=1024, blank=True, null=True)  # Field name made lowercase.
    fecha_nacimiento_artista = models.DateField(db_column='FECHA_NACIMIENTO_ARTISTA', blank=True, null=True)  # Field name made lowercase.
    valoracion_artista = models.IntegerField(db_column='VALORACION_ARTISTA', blank=True, null=True)  # Field name made lowercase.
    foto = models.ImageField(upload_to=url3)
    status = models.BooleanField(default=False)


    def __str__(self):
        return self.nombre_artista
        
    class Meta:
        managed = True
        db_table = 'artista'


    

class Cancion(models.Model):
    id_cancion = models.AutoField(db_column='ID_CANCION', primary_key=True)  # Field name made lowercase.
    id_disco = models.ForeignKey('Disco', db_column='ID_DISCO', blank=True, null=True)  # Field name made lowercase.
    nombre_cancion = models.CharField(db_column='NOMBRE_CANCION', max_length=60, blank=True, null=True)  # Field name made lowercase.
    duracion = models.IntegerField(db_column='DURACION', blank=True, null=True) # Field name made lowercase.
    val_cancion = models.IntegerField(db_column='VAL_CANCION', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'cancion'

    def __str__(self):
        return self.nombre_cancion


class Compra(models.Model):
    id_compra = models.AutoField(db_column='ID_COMPRA', primary_key=True)  # Field name made lowercase.
    id_disco = models.ForeignKey('Disco', db_column='ID_DISCO', blank=True, null=True)  # Field name made lowercase.
    fecha_compra = models.DateTimeField(db_column='FECHA_COMPRA', blank=True, null=True)  # Field name made lowercase.
    precio_final = models.IntegerField(db_column='PRECIO_FINAL', blank=True, null=True)  # Field name made lowercase.
    tipo_pago = models.CharField(db_column='TIPO_PAGO', max_length=10, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'compra'

def url(self, filename):
    ruta = "Discos/%s/%s" % (self.nombre_disco, str(filename))
    return ruta
    

class Disco(models.Model):


    id_disco = models.AutoField(db_column='ID_DISCO', primary_key=True)  # Field name made lowercase.
    id_artista = models.ForeignKey(Artista, db_column='ID_ARTISTA', blank=True,null=True)  # Field name made lowercase.
    id_compra = models.ForeignKey(Compra, db_column='ID_COMPRA', blank=True, null=True)  # Field name made lowercase.
    nombre_disco = models.CharField(db_column='NOMBRE_DISCO', max_length=60, blank=True, null=True)  # Field name made lowercase.
    fecha_lanzamiento = models.DateField(db_column='FECHA_LANZAMIENTO', blank=True, null=True)  # Field name made lowercase.
    genero = models.CharField(db_column='GENERO', max_length=100, blank=True, null=True)  # Field name made lowercase.
    resena = models.TextField(db_column='RESENA', max_length=1024, blank=True, null=True)  # Field name made lowercase.
    valoracion_disco = models.IntegerField(db_column='VALORACION_DISCO', blank=True, null=True)  # Field name made lowercase.
    precio = models.IntegerField(db_column='PRECIO', blank=True, null=True)  # Field name made lowercase.
    caratula = models.ImageField(upload_to=url)
    status = models.BooleanField(default=False)
    video = models.CharField(db_column='VIDEO', max_length=1024, blank=True, null=True)

    def __unicode__(self):
        return self.nombre_disco

    class Meta:
        managed = True
        db_table = 'disco'

    
def url2(self,filename):
    ruta = "Users/%s/%s"%(self.user.username,filename)
    return ruta


class userProfile(models.Model):

    user        =   models.OneToOneField(User, related_name="profile")
    photo       =   models.ImageField(upload_to=url2)
    fecha_nacimiento_user = models.DateField(db_column='FECHA_NACIMIENTO_USER',blank=True, null=True)  # Field name made lowercase.
    descuento = models.IntegerField(db_column='DESCUENTO', blank=True, null=True)  # Field name made lowercase.
    direccion = models.CharField(db_column='DIRECCION', max_length=40, blank=True, null=True)  # Field name made lowercase.
    valoracion_user = models.IntegerField(db_column='VALORACION_USER', blank=True, null=True)  # Field name made lowercase.

    def __unicode__(self):
        return self.user.username

class ComentaDisco(models.Model):

    id_cd = models.AutoField(db_column='ID_CD', primary_key=True)  # Field name made lowercase.
    user = models.ForeignKey(User, db_column='ID_USER', unique=False , blank=True,null=True)  # Field name made lowercase.
    titulo = models.CharField(db_column='TITULO', max_length=40, blank=True, null=True)
    comentario = models.TextField(db_column='COMENTARIO', max_length=200, blank=True, null=True)
    id_disco = models.ForeignKey(Disco, db_column='ID_DISCO', unique=False, blank=True,null=True)  # Field name made lowercase.

    #agregar id_disco
class ValoraDisco(models.Model):

    id_vd = models.AutoField(db_column='ID_VD', primary_key=True)  # Field name made lowercase.
    user = models.ForeignKey(User, db_column='ID_USER')
    id_disco = models.ForeignKey(Disco, db_column='ID_DISCO')  # Field name made lowercase.
    valoracion_disco = models.IntegerField(db_column='VALORACION_DISCO')

    class Meta:
        managed = True
        db_table = 'valoradisco'
        unique_together = (('user', 'id_disco'),)

rajim/views.py
 # -*- coding: utf-8 -*-
from django.shortcuts import render
from django.shortcuts import redirect
from rajim.models import *
from django.template import loader, Context, RequestContext
from .forms import *
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.shortcuts import render_to_response
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import User
from django.contrib.auth.decorators import login_required
from django.core.mail.message import EmailMultiAlternatives
from django.http.response import HttpResponseRedirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMessage

# Create your views here.

def Artistas(request,id_artista):
    artista = Artista.objects.get(id_artista=id_artista)
    disco = Disco.objects.filter(id_artista=id_artista).order_by('id_disco')
    return render(request,'rajim/Artista.html',{'artista':artista, 'disco':disco},context_instance=RequestContext(request))

def BusquedaArtista(request):
    form = SearchForm()
    artistas = Artista.objects.filter(status=True)
    if request.method == "POST":
        form= SearchForm(request.POST)
        if form.is_valid():
            buscar = form.cleaned_data['buscar']
            artistass =Artista.objects.filter(nombre_artista__contains=buscar)
            return render(request,'rajim/BusquedaArtista2.html',{'form' :form,'artistass':artistass,'buscar' :buscar},context_instance=RequestContext(request))
    form = SearchForm()
    return render(request,'rajim/BusquedaArtista.html',{'form':form, 'artistas':artistas},context_instance=RequestContext(request))    

def Album(request,id_disco):
    user = request.user
    disco = Disco.objects.get(id_disco=id_disco)
    canciones = Cancion.objects.filter(id_disco=id_disco).order_by('id_cancion')
    form = ComentaDiscoForm()
    #form2 = ValoraDiscoForm()
    if request.method == "POST":
        form = ComentaDiscoForm(request.POST)
        #form2 = ValoraDiscoForm(request.POST)
        if form.is_valid:
            ComentaDisco = form.save(commit=False)
            #ValoraDisco = form.save(commit= False)
            ComentaDisco.user = user
            #ValoraDisco.user = user
            ComentaDisco.id_disco = disco
            #ValoraDiscoForm.id_disco = disco
            #valoracion = form2.cleaned_data['valoracion']
            #ValoraDisco.valoracion_disco= valoracion
            #ValoraDisco.save()
            ComentaDisco.save()
            #comentarios = ComentaDisco.objects.filter(id_disco=id_disco)

            return render(request,'rajim/Disco.html',{'disco':disco, 'canciones':canciones, 'form':form, 'comentarios':comentarios},context_instance=RequestContext(request))


             
    return render(request,'rajim/Disco.html',{'disco':disco, 'canciones':canciones, 'form':form},context_instance=RequestContext(request))


def BusquedaAlbum(request):
    form = SearchForm()
    discos = Disco.objects.filter(status=True)
    if request.method == "POST":
        form= SearchForm(request.POST)
        if form.is_valid():
            buscar = form.cleaned_data['buscar']
            discoss =Disco.objects.filter(nombre_disco__contains=buscar)
            return render(request,'rajim/BusquedaDisco2.html',{'form' :form,'discoss':discoss,'buscar' :buscar},context_instance=RequestContext(request))
    form = SearchForm()
    return render(request,'rajim/BusquedaDisco.html',{'form' :form,'discos':discos},context_instance=RequestContext(request))



def Contacto(request):
    user=request.user
    if request.method=='POST':
        form=Reporte(request.POST)
        if form.is_valid():
            user_form = UserForm(request.POST, instance=request.user)
            asunto = dict(CHOICES) [form.cleaned_data['Asunto']]
            nombre = user.username #user_form
            mensaje= form.cleaned_data['Mensaje']
            from_email =user.email #user_form
            
            
            #mail=EmailMessage(asunto,mensaje,from_email,to=['diego.jefecito@gmail.com'])
            #mail.send()
            
            html_content = "<h2>[%s] <br>Nombre:%s <br> Mensaje:%s"%(from_email,nombre,mensaje)
            msg = EmailMultiAlternatives(asunto, mensaje, from_email, to=['diego.jefecito@gmail.com'])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            #msg=EmailMultiAlternatives('Correo de Contacto',html_content,[to_admin])
            #msg.attach_alternative(html_content, "text/html")
            #msg.send()
        return HttpResponseRedirect('/')
    else:
        form=Reporte()
        
    return render_to_response('rajim/Contacto.html',{'form':form,}, context_instance=RequestContext(request))
		

def Registrar(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
    else:
        form = RegisterForm()
        if request.method == "POST":
            form= RegisterForm(request.POST)
            if form.is_valid():
                usuario = form.cleaned_data['username']
                email = form.cleaned_data['email']
                password_one = form.cleaned_data['password_one']
                password_two = form.cleaned_data['password_two']
                u = User.objects.create_user(username=usuario, email=email,password=password_one)
                u.save()
                perfil = userProfile(user=u, photo='\static\Fingeso\img\perfilphoto.jpg')
                perfil.save()
                return render(request,'rajim/Registrar2.html',context_instance=RequestContext(request))
            else:
                return render(request,'rajim/Registrar.html',{'form':form},context_instance=RequestContext(request))

        return render(request,'rajim/Registrar.html',{'form':form},context_instance=RequestContext(request))

def Ingresar(request):
    mensaje = ""
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
    else:
        if request.method == "POST":
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                usuario = authenticate(username=username, password=password)
                if usuario is not None and usuario.is_active:
                    login(request,usuario)
                    return HttpResponseRedirect('/')
                else:
                    mensaje = "usuario y/o password incorrecto"
        form = LoginForm()
        return render(request,'rajim/Ingresar.html',{'form':form, 'mensaje':mensaje},context_instance=RequestContext(request))

def CerrarSesion(request):
    logout(request)
    return HttpResponseRedirect('/')
    
def Ranking(request):
    rankartista = Artista.objects.filter(valoracion_artista__isnull=False).order_by('-valoracion_artista')
    rankdisco = Disco.objects.filter(valoracion_disco__isnull=False).order_by('-valoracion_disco')
    rankuser = userProfile.objects.filter(valoracion_user__isnull=False).order_by('-valoracion_user')
    return render(request,'rajim/Ranking.html',{ 'rankdisco':rankdisco,'rankartista':rankartista ,'rankuser':rankuser})
def Registrar2(request):
    return render(request, 'rajim/Registrar2.html',{})
def Perfil(request):
    if request.user.is_authenticated():
        return render(request, 'rajim/Perfil.html',{})

    else:
        return HttpResponseRedirect('/')

    return render(request, 'rajim/Perfil.html',{})

def EditarPerfil(request):
    if request.user.is_authenticated():
        if request.method == 'POST':
            # formulario enviado
            user_form = UserForm(request.POST, instance=request.user)
            perfil_form = PerfilForm(request.POST, request.FILES, instance=request.user.profile)
            if user_form.is_valid() and perfil_form.is_valid():
                # formulario validado correctamente
                user_form.save()
                perfil_form.save()

            return HttpResponseRedirect('/rajim/Perfil.html')

        else:
            # formulario inicial
            user_form = UserForm(instance=request.user)
            perfil_form = PerfilForm(instance=request.user.profile)
        return render(request,'rajim/EditarPerfil.html', { 'user_form': user_form,  'perfil_form': perfil_form }, context_instance=RequestContext(request))
    else:
        return HttpResponseRedirect('/')

rajim/templates/rajim/Artista.html
{% extends "rajim/base2.html" %}
{% block content %}

<title>{% block title %}Artista{% endblock %}</title>
  <!-- end header -->
  <section id="inner-headline">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="breadcrumb">
          <li><a href="/"><i class="fa fa-home"></i></a>
            <i class="icon-angle-right"></i></li>
          
          <li><a href="/rajim/BusquedaArtista.html">Buscar</a><i class="icon-angle-right"></i></li>
          <li><a href="/rajim/BusquedaArtista.html">Artista</a><i class="icon-angle-right"></i></li>
          <li class="active">{{artista.nombre_artista}}</li>

        </ul>
      </div>
    </div>
  </div>

 
  </section>
  
  <div id="w">    
       
    <div class="crsl-items" data-navigation="navbtns">
      <div class="crsl-wrap">
        <div class="crsl-item">
          <div class="thumbnail">
           
            <img src="/media/{{artista.foto}}" alt=""width="380" height="300">
            <span class="postdate">{{artista.fecha_nacimiento_artista}}</span>
          </div>
          <h3><a href="#">{{artista.nombre_artista}}</a></h3>

          <div class="col-lg-12">
            <hr>
            <div class="col-lg-6">
              <br>
              <div class="container">
                <div class="row">
                  <div class="col-lg-4">
                    <p ><strong>Artista:</strong> {{artista.nombre_artista}}</p>
                    <p ><strong>Fecha de nacimiento:</strong> {{artista.fecha_nacimiento_artista}}</p>
                    <p ><strong>Calificacion :</strong> {{artista.valoracion_artista}} </p>
                    <p><strong>Reseña :</strong>{{artista.resena}}</p>
                    <strong class="choice">Evalualo!</strong>
                    <br>
                    <div id="jRate" style="height:50px;width: 200px;"></div>
                  </div>
                  <div class="col-lg-4">
                    <div class="list-group">
                      <a href="#" class="list-group-item active">Discos de {{artista.nombre_artista}}</a>
                      {% for i in disco %}
                      <a href="/rajim/Disco/{{i.id_disco}}" class="list-group-item"><p>{{i.nombre_disco}}</p></a>
                      {% endfor %}
                    </div>
                  </div>




                </div>
              </div>
            </div>
            <br>
            <br>
            
        </div>
      </div><!-- post #1 -->       
    </div><!-- @end .crsl-wrap -->
  </div><!-- @end .crsl-items -->
    





{% endblock content %}

rajim/templates/rajim/BusquedaArtista.html
{% extends "rajim/base2.html" %}
{% block content %}
<title>{% block title %}Artista{% endblock %}</title>
  <!-- end header -->
  <section id="inner-headline">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="breadcrumb">
          <li><a href="/"><i class="fa fa-home"></i></a>
            <i class="icon-angle-right"></i></li>
          
          <li><a href="#">Buscar</a><i class="icon-angle-right"></i></li>
          <li class="active">Artista</li>

        </ul>
        
             
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
        <div>

        </div>
    </div>
  </div>
  </section>
  <hr>

<div class="col-lg-6">
  <form  action=""  method="post"> 
      {% csrf_token %}
      {{ form.as_p }}
      </form>
</div>
<br>
<br>

    <div class="list-group">
    <a href="#" class="list-group-item active" align="center">
    <H1>Artistas</H1>
    </a>
    {% for p in artistas %}
      <a href="Artista/{{p.id_artista}}" class="list-group-item" align ="center">{{p.nombre_artista}}</a>
    {% endfor %}
    </div>

  {% endblock content %}

rajim/templates/rajim/BusquedaArtista2.html
{% extends "rajim/base2.html" %}
{% block content %}
<title>{% block title %}Artista{% endblock %}</title>
  <!-- end header -->
  <section id="inner-headline">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="breadcrumb">
          <li><a href="/"><i class="fa fa-home"></i></a>
            <i class="icon-angle-right"></i></li>
          
          <li><a href="#">Buscar</a><i class="icon-angle-right"></i></li>
          <li class="active">Artista</li>

        </ul>
        
             
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
        <div>

        </div>
    </div>
  </div>
  </section>
  <br>
  <h1>Coincidencias para "{{buscar}}": </h1>



          <div class="col-lg-12">
           {% for p in artistass %}
           <h1><a href="Artista/{{p.id_artista}}">{{p.nombre_artista}}</a></h1>

           {% endfor %}
        </div>

  {% endblock content %}

rajim/templates/rajim/BusquedaDisco.html
{% extends "rajim/base2.html" %}
{% block content %}
<title>{% block title %}Disco{% endblock %}</title>
  <!-- end header -->
  <section id="inner-headline">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="breadcrumb">
          <li><a href="/"><i class="fa fa-home"></i></a>
            <i class="icon-angle-right"></i></li>
          
          <li><a href="#">Buscar</a><i class="icon-angle-right"></i></li>
          <li class="active">Disco</li>

        </ul>
        
             
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
        <div>

        </div>
    </div>
  </div>
  </section>
  <hr>

<div class="col-lg-6">
  <form  action=""  method="post"> 
      {% csrf_token %}
      {{ form.as_p }}
      </form>
</div>
<br>
<br>

    <div class="list-group">
    <a href="#" class="list-group-item active" align="center">
    <H1>Discos</H1>
    </a>
    {% for p in discos %}
      <a href="Disco/{{p.id_disco}}" class="list-group-item" align ="center">{{p.nombre_disco}}</a>
    {% endfor %}
    </div>

  {% endblock content %}

rajim/templates/rajim/BusquedaDisco2.html
{% extends "rajim/base2.html" %}
{% block content %}
<title>{% block title %}Disco{% endblock %}</title>
  <!-- end header -->
  <section id="inner-headline">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <ul class="breadcrumb">
          <li><a href="/"><i class="fa fa-home"></i></a>
            <i class="icon-angle-right"></i></li>
          
          <li><a href="#">Buscar</a><i class="icon-angle-right"></i></li>
          <li class="active">Disco</li>

        </ul>
        
             
      </div>
    </div>
  </div>


  <div class="container">
    <div class="row">
        <div>

        </div>
    </div>
  </div>
  </section>
  <br>
  <h1>Coincidencias para "{{buscar}}": </h1>



          <div class="col-lg-12">
           {% for p in discoss %}
           <h1><a href="Disco/{{p.id_disco}}">{{p.nombre_disco}}</a></h1>

           {% endfor %}
        </div>

  {% endblock content %}

rajim/templates/rajim/Contacto.html
{% extends "rajim/base2.html" %}
{% block content %}

<title>{% block title %}Contacto{% endblock %}</title>
	<!-- end header -->
	<section id="inner-headline">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<ul class="breadcrumb">
					<li><a href="/"><i class="fa fa-home"></i></a><i class="icon-angle-right"></i></li>
					<li class="active">Contacto</li>
				</ul>
			</div>
		</div>
	</div>
	</section>
	<section id="content">
	<div class="map">
		<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6657.791846963416!2d-70.68294653436278!3d-33.452017960329435!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x570cc870711695a9!2sDepartamento+de+Ingenier%C3%ADa+Inform%C3%A1tica+USACH!5e0!3m2!1ses!2scl!4v1433117887287" width="600" height="450" frameborder="0" style="border:0"></iframe>
	</div>
	<div class="container">

		<div class="row">
			<div class="col-lg-12">
			{% if user.is_authenticated %}
				<h2>Mantente en contacto con nosotros y <strong>reporta cualquier error que presencies en la pagina<br><br></strong></h2>
					
			<div class="container">
				 <form id="Reporte" autocomplete="on"  method="post">{% csrf_token %} 
                   
								{{ form.Asunto }}
								<br><br>
                                {{ form.Mensaje }}                                                
                                
								</div>
								<center>
                                         <button class="btn btn-theme margintop10 pull-left" type="submit">Enviar mensaje</button>
										 </center>
								<span class="pull-right margintop20">* Porfavor rellena todos los campos marcados.</span>
                            </form>
							  {% endif %}
			</div>
		</div>
	</div>
	</section>
{% endblock content %}

rajim/templates/rajim/EditarPerfil.html
{% extends "rajim/base2.html" %}
{% block content %}
<title>{% block title %}Editar Perfil{% endblock %}</title>
	<section id="inner-headline">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<ul class="breadcrumb">
					<li><a href="/"><i class="fa fa-home"></i></a>
						<i class="icon-angle-right"></i></li>
					
					<li class="active">Editar Perfil</li>
				</ul>
			</div>
		</div>
	</div>
	</section>
<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">

       <br>
		<p class=" text-info"> </p>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">{{ user.username }}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img name="photo" alt="User Pic" src="{{MEDIA_URL}}{{user.profile.photo}}" class="img-circle"> </div>
                <form action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}

              			    <input id="id_photo" type="file" name="photo"/>{{form.photo}}

              			    
              			   

					<div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                    	<tr>
	                        <td>Username:</td>
	                        <td> {{ user_form.username }}</td>
                      	</tr>
                      <tr>
                        <td>Nombre:</td>
                        <td>{{user_form.first_name}}</td>
                      </tr>
                      <tr>
                        <td>Apellido:</td>
                        <td>{{user_form.last_name}}</td>
                      </tr>
                      <tr>
                        <td>Ultimo login:</td>
                        <td>{{user.last_login}}</td>
                      </tr>
                        <tr>
                        <td>Fecha registro:</td>
                        <td>{{user.date_joined}}</td>
                      </tr>
                      <tr>
                        <td>Fecha de nacimiento</td>
                        <td>{{perfil_form.fecha_nacimiento_user}}</td>
                      </tr>
                      <tr>
                        <td>Direccion</td>
                        <td>{{ perfil_form.direccion}}</td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td>{{ user_form.email }}</td>
                      </tr>
                      
                     
                    </tbody>
                  </table>
              		

                  <div class="col-sm-6">
                  <h1>{{user.profile.valoracion_user}}</h1>
                  <h1><a href="#" class="btn btn-warning">valoracion</a></h1>	
                  
              	</div>
              	<div class="col-sm-6">
              	 <h1>{{user.profile.descuento}}</h1>
                  <h1><a href="#" class="btn btn-success">descuento</a></h1>
                 </div>	
                </div>
              </div>
            </div>
		 <div class="panel-footer">
                        <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" href="/rajim/Contacto.html"class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                        <span class="pull-right">
                        <input type="submit" class="btn btn-sm btn-primary" value="Guardar cambios">
						</form>
                        </span>
                    </div>
            
            
          </div>
        </div>
      </div>
    </div>
<script type="text/javascript">
$(document).ready(function() {
    var panels = $('.user-infos');
    var panelsButton = $('.dropdown-user');
    panels.hide();

    //Click dropdown
    panelsButton.click(function() {
        //get data-for attribute
        var dataFor = $(this).attr('data-for');
        var idFor = $(dataFor);

        //current button
        var currentButton = $(this);
        idFor.slideToggle(400, function() {
            //Completed slidetoggle
            if(idFor.is(':visible'))
            {
                currentButton.html('<i class="glyphicon glyphicon-chevron-up text-muted"></i>');
            }
            else
            {
                currentButton.html('<i class="glyphicon glyphicon-chevron-down text-muted"></i>');
            }
        })
    });


    $('[data-toggle="tooltip"]').tooltip();

    $('button').click(function(e) {
        e.preventDefault();
        alert("This is a demo.\n :-)");
    });
});
</script>

{% endblock content %}